version: '3.8'

# BD POSTGRES
services:
  postgres:
    image: postgres:15
    env_file:
      - ./bd.env

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U knowledge_user -d knowledge_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - back-net

# REDIS CACHE
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - back-net

# BACKEND
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./backend.env
    restart: always
    networks:
      - back-net

  # FRONTEND
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend.env
    restart: always
    networks:
      - front-net
      - back-net

# Criação das Networks limitando acesso entre os serviços      
networks:
  front-net:
    driver: bridge
  back-net:
    driver: bridge
    internal: true


