name: Deploy Knowledge App no Azure

# Executar manualmente 
on:
  workflow_dispatch: # Permite que o workflow seja executado manualmente a partir da interface do GitHub.

# Definir os jobs para o workflow
jobs:
    deploy:
        runs-on: ubuntu-latest # Especifica o ambiente de execução para o job.

        steps:
            # Passo 1: Verificar o código-fonte do repositório
            - name: Checkout repository # Nome do Step 1
              uses: actions/checkout@v4 # Ação para fazer checkout do código-fonte do repositório.

            # Passo 2: Configurar o Azure CLI
            - name: Azure Login # Nome do Step 2
              uses: azure/login@v1 # Ação para autenticar no Azure.
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }} # Usar as credenciais armazenadas como segredo no GitHub.
            
            # Passo 3: Setup do Terraform
            - name: Setup Terraform # Nome do Step 3
              uses: hashicorp/setup-terraform@v2 # Ação para configurar o Terraform.
              with:
                terraform_version: 1.5.0 # Especifica a versão do Terraform a ser usada.
            
            # Passo 4: Gerar o arquivo de variáveis do Terraform
            - name: Gerar deploy.tfvars # Nome do Step 4
              env:
                SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
                CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
                CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
                TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
                RG_LOCATION: ${{ vars.TF_RG_LOCATION }}
                CR_SKU: ${{ vars.TF_CR_SKU }}
                ACG_IP_ADDRESS_TYPE: ${{ vars.TF_ACG_IP_ADDRESS_TYPE }}
                ACG_DNS_NAME_LABEL: ${{ vars.TF_ACG_DNS_NAME_LABEL }}
                ACG_OS_TYPE: ${{ vars.TF_ACG_OS_TYPE }}
                CT_FRONTEND_CPU: ${{ vars.TF_CT_FRONTEND_CPU }}
                CT_FRONTEND_MEMORY: ${{ vars.TF_CT_FRONTEND_MEMORY }}
                API_URL: ${{ vars.TF_API_URL }}
                CT_FRONTEND_PORT: ${{ vars.TF_CT_FRONTEND_PORT }}
                CT_FRONTEND_PROTOCOL: ${{ vars.TF_CT_FRONTEND_PROTOCOL }}
                CT_BACKEND_CPU: ${{ vars.TF_CT_BACKEND_CPU }}
                CT_BACKEND_MEMORY: ${{ vars.TF_CT_BACKEND_MEMORY }}
                CT_BACKEND_PORT: ${{ vars.TF_CT_BACKEND_PORT }}
                CT_BACKEND_PROTOCOL: ${{ vars.TF_CT_BACKEND_PROTOCOL }}
                DATABASE_URL: ${{ secrets.TF_DATABASE_URL }}
                REDIS_URL: ${{ secrets.TF_REDIS_URL }}
                CT_POSTGRES_CPU: ${{ vars.TF_CT_POSTGRES_CPU }}
                CT_POSTGRES_MEMORY: ${{ vars.TF_CT_POSTGRES_MEMORY }}
                POSTGRES_DB: ${{ vars.TF_POSTGRES_DB }}
                POSTGRES_USER: ${{ vars.TF_POSTGRES_USER }}
                POSTGRES_PASSWORD: ${{ secrets.TF_POSTGRES_PASSWORD }}
                CT_POSTGRES_PORT: ${{ vars.TF_CT_POSTGRES_PORT }}
                CT_POSTGRES_PROTOCOL: ${{ vars.TF_CT_POSTGRES_PROTOCOL }}
                CT_REDIS_CPU: ${{ vars.TF_CT_REDIS_CPU }}
                CT_REDIS_MEMORY: ${{ vars.TF_CT_REDIS_MEMORY }}
              run: |
                {
                  echo "subscription_id      = \"$SUBSCRIPTION_ID\""
                  echo "client_id            = \"$CLIENT_ID\""
                  echo "client_secret        = \"$CLIENT_SECRET\""
                  echo "tenant_id            = \"$TENANT_ID\""
                  echo "rg_location          = \"$RG_LOCATION\""
                  echo "cr_sku               = \"$CR_SKU\""
                  echo "acg_ip_address_type  = \"$ACG_IP_ADDRESS_TYPE\""
                  echo "acg_dns_name_label   = \"$ACG_DNS_NAME_LABEL\""
                  echo "acg_os_type          = \"$ACG_OS_TYPE\""
                  echo "ct_frontend_cpu      = $CT_FRONTEND_CPU"
                  echo "ct_frontend_memory   = $CT_FRONTEND_MEMORY"
                  echo "api_url              = \"$API_URL\""
                  echo "ct_frontend_port     = $CT_FRONTEND_PORT"
                  echo "ct_frontend_protocol = \"$CT_FRONTEND_PROTOCOL\""
                  echo "ct_backend_cpu       = $CT_BACKEND_CPU"
                  echo "ct_backend_memory    = $CT_BACKEND_MEMORY"
                  echo "ct_backend_port      = $CT_BACKEND_PORT"
                  echo "ct_backend_protocol  = \"$CT_BACKEND_PROTOCOL\""
                  echo "database_url         = \"$DATABASE_URL\""
                  echo "redis_url            = \"$REDIS_URL\""
                  echo "ct_postgres_cpu      = $CT_POSTGRES_CPU"
                  echo "ct_postgres_memory   = $CT_POSTGRES_MEMORY"
                  echo "postgres_db          = \"$POSTGRES_DB\""
                  echo "postgres_user        = \"$POSTGRES_USER\""
                  echo "postgres_password    = \"$POSTGRES_PASSWORD\""
                  echo "ct_postgres_port     = $CT_POSTGRES_PORT"
                  echo "ct_postgres_protocol = \"$CT_POSTGRES_PROTOCOL\""
                  echo "ct_redis_cpu         = $CT_REDIS_CPU"
                  echo "ct_redis_memory      = $CT_REDIS_MEMORY"
                } > terraform/deploy.tfvars

            # Passo 5: Inicializar e preparar o Terraform
            - name: Terraform Init # Nome do Step 5
              run: |
                cd terraform # Navega para o diretório onde estão os arquivos do Terraform.
                export ARM_CLIENT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
                export ARM_CLIENT_SECRET="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
                export ARM_SUBSCRIPTION_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}"
                export ARM_TENANT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
                ARM_ACCESS_KEY=$(az storage account keys list \
                  --resource-group "rg-labinfo-prod-eus2-001" \
                  --account-name "strterraformbackend001" \
                  --query "[0].value" -o tsv)
                echo "ARM_ACCESS_KEY=$ARM_ACCESS_KEY" >> $GITHUB_ENV
                export ARM_ACCESS_KEY

                terraform init

            # Passo 6: Planejar a aplicação da infraestrutura
            - name: Terraform Plan # Nome do Step 6
              run: |
                cd terraform
                export ARM_CLIENT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
                export ARM_CLIENT_SECRET="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
                export ARM_SUBSCRIPTION_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}"
                export ARM_TENANT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"

                export ARM_ACCESS_KEY="${{ env.ARM_ACCESS_KEY }}"

                terraform plan -var-file="deploy.tfvars" -target=module.rg-module -target=module.acr-module -target=module.acg-module

            
            
            # Passo 7: Aplicar a infraestrutura básica no Azure
            - name: Terraform Apply # Nome do Step 7
              run: |
                cd terraform
                export ARM_CLIENT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
                export ARM_CLIENT_SECRET="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
                export ARM_SUBSCRIPTION_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}"
                export ARM_TENANT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"

                export ARM_ACCESS_KEY="${{ env.ARM_ACCESS_KEY }}"

                # Aplicar apenas os recursos essenciais para criar a infraestrutura básica (Resource Group, Container Registry e Container Group)
                terraform apply -auto-approve -var-file="deploy.tfvars" -target=module.rg-module -target=module.acr-module -target=module.acg-module
            
            
            # Passo 8: Build das Imagens do Docker (Frontend e Backend)
            - name: Build and Push Docker Images # Nome do Step 8
              run: |
                export ARM_CLIENT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
                export ARM_CLIENT_SECRET="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
                export ARM_SUBSCRIPTION_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}"
                export ARM_TENANT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
                export ARM_ACCESS_KEY="${{ env.ARM_ACCESS_KEY }}"

                # Buscar informações do Azure Container Registry (ACR) criado pelo Terraform
                ACR_SERVER=$(cd terraform && terraform output -raw cr_login_server)
                ACR_USERNAME=$(cd terraform && terraform output -raw cr_admin_username)
                ACR_PASSWORD=$(cd terraform && terraform output -raw cr_admin_password)

                # Fazer login no Azure Container Registry (ACR)
                echo $ACR_PASSWORD | docker login $ACR_SERVER -u $ACR_USERNAME --password-stdin

                # Build e Push da Imagem do Frontend
                docker build -t $ACR_SERVER/kbapp-frontend:latest -f ./frontend/Dockerfile ./frontend
                docker push $ACR_SERVER/kbapp-frontend:latest

                # Build e Push da Imagem do Backend
                docker build -t $ACR_SERVER/kbapp-backend:latest -f ./backend/Dockerfile ./backend
                docker push $ACR_SERVER/kbapp-backend:latest

            # Passo 9: Aplicar as mudanças finais no Azure para atualizar os containers com as novas imagens
            - name: Deploy dos Containers no Azure # Nome do Step 9
              run: |
                cd terraform
                export ARM_CLIENT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
                export ARM_CLIENT_SECRET="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
                export ARM_SUBSCRIPTION_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}"
                export ARM_TENANT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
                export ARM_ACCESS_KEY="${{ env.ARM_ACCESS_KEY }}"

                # Aplicar as mudanças finais e forçar a recriação do Container Group com as novas imagens
                terraform apply -auto-approve -var-file="deploy.tfvars" -replace="module.acg-module.azurerm_container_group.acg"

            # Passo 10: URL de Acesso à Aplicação
            - name: Output URL # Nome do Step 10
              run: |
                cd terraform
                export ARM_CLIENT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}"
                export ARM_CLIENT_SECRET="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}"
                export ARM_SUBSCRIPTION_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}"
                export ARM_TENANT_ID="${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
    
                # Obter a URL de acesso à aplicação a partir do Terraform output
                APP_URL=$(terraform output -raw app_url)
                echo "A aplicação está disponível em: $APP_URL"