name: Deploy Knowledge App no Azure

# Executar manualmente 
on:
  workflow_dispatch: # Permite que o workflow seja executado manualmente a partir da interface do GitHub.

# Definir os jobs para o workflow
jobs:
    deploy:
        runs-on: ubuntu-latest # Especifica o ambiente de execução para o job.

        env:
            ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
            ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
            ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
            ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
            ARM_ACCESS_KEY: ${{ secrets.TF_BACKEND_ACCESS_KEY }}
            TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
            TF_VAR_client_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
            TF_VAR_client_secret: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
            TF_VAR_tenant_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
            TF_VAR_rg_location: ${{ vars.TF_RG_LOCATION }}
            TF_VAR_cr_sku: ${{ vars.TF_CR_SKU }}
            TF_VAR_acg_ip_address_type: ${{ vars.TF_ACG_IP_ADDRESS_TYPE }}
            TF_VAR_acg_dns_name_label: ${{ vars.TF_ACG_DNS_NAME_LABEL }}
            TF_VAR_acg_os_type: ${{ vars.TF_ACG_OS_TYPE }}
            TF_VAR_ct_frontend_cpu: ${{ vars.TF_CT_FRONTEND_CPU }}
            TF_VAR_ct_frontend_memory: ${{ vars.TF_CT_FRONTEND_MEMORY }}
            TF_VAR_api_url: ${{ vars.TF_API_URL }}
            TF_VAR_ct_frontend_port: ${{ vars.TF_CT_FRONTEND_PORT }}
            TF_VAR_ct_frontend_protocol: ${{ vars.TF_CT_FRONTEND_PROTOCOL }}
            TF_VAR_ct_backend_cpu: ${{ vars.TF_CT_BACKEND_CPU }}
            TF_VAR_ct_backend_memory: ${{ vars.TF_CT_BACKEND_MEMORY }}
            TF_VAR_ct_backend_port: ${{ vars.TF_CT_BACKEND_PORT }}
            TF_VAR_ct_backend_protocol: ${{ vars.TF_CT_BACKEND_PROTOCOL }}
            TF_VAR_database_url: ${{ secrets.TF_DATABASE_URL }}
            TF_VAR_redis_url: ${{ secrets.TF_REDIS_URL }}
            TF_VAR_ct_postgres_cpu: ${{ vars.TF_CT_POSTGRES_CPU }}
            TF_VAR_ct_postgres_memory: ${{ vars.TF_CT_POSTGRES_MEMORY }}
            TF_VAR_postgres_db: ${{ vars.TF_POSTGRES_DB }}
            TF_VAR_postgres_user: ${{ vars.TF_POSTGRES_USER }}
            TF_VAR_postgres_password: ${{ secrets.TF_POSTGRES_PASSWORD }}
            TF_VAR_ct_postgres_port: ${{ vars.TF_CT_POSTGRES_PORT }}
            TF_VAR_ct_postgres_protocol: ${{ vars.TF_CT_POSTGRES_PROTOCOL }}
            TF_VAR_ct_redis_cpu: ${{ vars.TF_CT_REDIS_CPU }}
            TF_VAR_ct_redis_memory: ${{ vars.TF_CT_REDIS_MEMORY }}
            TF_VAR_frontend_nr_license_key: ${{ secrets.TF_FRONTEND_NR_LICENSE_KEY }}

        steps:
            # Passo 1: Verificar o código-fonte do repositório
            - name: Checkout repository # Nome do Step 1
              uses: actions/checkout@v4 # Ação para fazer checkout do código-fonte do repositório.

            # Passo 2: Configurar o Azure CLI
            - name: Azure Login # Nome do Step 2
              uses: azure/login@v1 # Ação para autenticar no Azure.
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }} # Usar as credenciais armazenadas como segredo no GitHub.
            
            # Passo 3: Setup do Terraform
            - name: Setup Terraform # Nome do Step 3
              uses: hashicorp/setup-terraform@v2 # Ação para configurar o Terraform.
              with:
                terraform_version: 1.5.0 # Especifica a versão do Terraform a ser usada.
                terraform_wrapper: false # Desabilita o wrapper para permitir uso de terraform output -raw em subshell

            # Passo 4: Inicializar e preparar o Terraform
            - name: Terraform Init # Nome do Step 4
              run: |
                cd terraform
                terraform init

            # Passo 5: Planejar a aplicação da infraestrutura
            - name: Terraform Plan # Nome do Step 5
              run: |
                cd terraform
                terraform plan -target=module.rg-module -target=module.acr-module

            # Passo 6: Aplicar apenas RG e ACR (sem Container Group)
            - name: Terraform Apply # Nome do Step 6
              run: |
                cd terraform
                terraform apply -auto-approve -target=module.rg-module -target=module.acr-module
            
            
            # Passo 7: Build das Imagens do Docker (Frontend e Backend)
            - name: Build and Push Docker Images # Nome do Step 7
              run: |                # Buscar informações do Azure Container Registry (ACR) criado pelo Terraform
                ACR_SERVER=$(cd terraform && terraform output -raw cr_login_server)
                ACR_USERNAME=$(cd terraform && terraform output -raw cr_admin_username)
                ACR_PASSWORD=$(cd terraform && terraform output -raw cr_admin_password)

                # Fazer login no Azure Container Registry (ACR)
                echo $ACR_PASSWORD | docker login $ACR_SERVER -u $ACR_USERNAME --password-stdin

                # Build e Push da Imagem do Frontend
                docker build -t $ACR_SERVER/kbapp-frontend:latest -f ./frontend/Dockerfile ./frontend
                docker push $ACR_SERVER/kbapp-frontend:latest

                # Build e Push da Imagem do Backend
                docker build -t $ACR_SERVER/kbapp-backend:latest -f ./backend/Dockerfile ./backend
                docker push $ACR_SERVER/kbapp-backend:latest

            # Passo 8: Criar/atualizar Container Group com as imagens recém publicadas
            - name: Deploy dos Containers no Azure # Nome do Step 8
              run: |
                cd terraform
                terraform apply -auto-approve

            # Passo 9: URL de Acesso à Aplicação
            - name: Output URL # Nome do Step 9
              run: |
                cd terraform
                # Obter a URL de acesso à aplicação a partir do Terraform output
                APP_URL=$(terraform output -raw app_url)
                echo "A aplicação está disponível em: $APP_URL"